debug: true
spring:
  application:
    name: mima-cloud-oauth-resource
  redis:
    database: 1
    host: 10.56.21.3
    port: 6379
    password: LhPJNMF3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
server:
  port: 9909
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    service-url:
      defaultZone: http://kevin:123456@localhost:8761/eureka/

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
    com.alibaba.druid: DEBUG
security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
    resource:
      # 使用令牌信息，可以设置为false以使用用户信息。 走user-info-uri接口去获取用户信息
      #prefer-token-info: false
      # 使用令牌信息，true。 走token-info-uri接口去获取用户信息
      # 这个时候使用的是client_credentials授权模式
      # 所以client-id、client-secret必须配置
      prefer-token-info: true
      #单点访问方式认证中心,查询用户信息
      #user-info-uri: http://localhost:9908/user
      #token-info-uri: http://localhost:9908/oauth/check_token
      #集群访问认证中心，查询用户信息
      user-info-uri: http://localhost:8801/mima-cloud-oauth-server/user
      token-info-uri: http://localhost:8801/mima-cloud-oauth-server/oauth/check_token
