spring:
  application:
    name: mima-cloud-consumer
server:
  port: 8802
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl: 
      defaultZone: http://kevin:123456@localhost:8761/eureka/
debug: true