debug: true
spring:
  application:
    name: mima-cloud-zuul-oauth
  main:
    allow-bean-definition-overriding: true
server:
  port: 7701
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://kevin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
#zuul:
#  mima-cloud-oauth-server:
#    path: /mima-cloud-oauth-server/**
#    sensitive-headers:
#    service-id: mima-cloud-oauth-server
#  mima-cloud-oauth-resource:
#    path: /mima-cloud-oauth-resource/**
#    sensitive-headers:
#    service-id: mima-cloud-oauth-resource
#  add-proxy-headers: true