spring:
  application:
    name: mcc-feign-hystrix
server:
  port: 8808
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
feign: 
  hystrix:
    #开启feign的hystrix支持,默认是false 
    enabled: true